/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlayersScriptSongIdImport } from './routes/players/script/$song-id'
import { Route as PlayersPlayerSongIdImport } from './routes/players/player/$song-id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayersScriptSongIdRoute = PlayersScriptSongIdImport.update({
  id: '/players/script/$song-id',
  path: '/players/script/$song-id',
  getParentRoute: () => rootRoute,
} as any)

const PlayersPlayerSongIdRoute = PlayersPlayerSongIdImport.update({
  id: '/players/player/$song-id',
  path: '/players/player/$song-id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/players/player/$song-id': {
      id: '/players/player/$song-id'
      path: '/players/player/$song-id'
      fullPath: '/players/player/$song-id'
      preLoaderRoute: typeof PlayersPlayerSongIdImport
      parentRoute: typeof rootRoute
    }
    '/players/script/$song-id': {
      id: '/players/script/$song-id'
      path: '/players/script/$song-id'
      fullPath: '/players/script/$song-id'
      preLoaderRoute: typeof PlayersScriptSongIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players/player/$song-id': typeof PlayersPlayerSongIdRoute
  '/players/script/$song-id': typeof PlayersScriptSongIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players/player/$song-id': typeof PlayersPlayerSongIdRoute
  '/players/script/$song-id': typeof PlayersScriptSongIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/players/player/$song-id': typeof PlayersPlayerSongIdRoute
  '/players/script/$song-id': typeof PlayersScriptSongIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/players/player/$song-id' | '/players/script/$song-id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/players/player/$song-id' | '/players/script/$song-id'
  id: '__root__' | '/' | '/players/player/$song-id' | '/players/script/$song-id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayersPlayerSongIdRoute: typeof PlayersPlayerSongIdRoute
  PlayersScriptSongIdRoute: typeof PlayersScriptSongIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayersPlayerSongIdRoute: PlayersPlayerSongIdRoute,
  PlayersScriptSongIdRoute: PlayersScriptSongIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/players/player/$song-id",
        "/players/script/$song-id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/players/player/$song-id": {
      "filePath": "players/player/$song-id.tsx"
    },
    "/players/script/$song-id": {
      "filePath": "players/script/$song-id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
