/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlayerSongIdImport } from './routes/player/$song-id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayerSongIdRoute = PlayerSongIdImport.update({
  id: '/player/$song-id',
  path: '/player/$song-id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/player/$song-id': {
      id: '/player/$song-id'
      path: '/player/$song-id'
      fullPath: '/player/$song-id'
      preLoaderRoute: typeof PlayerSongIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player/$song-id': typeof PlayerSongIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/$song-id': typeof PlayerSongIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/player/$song-id': typeof PlayerSongIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/player/$song-id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player/$song-id'
  id: '__root__' | '/' | '/player/$song-id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerSongIdRoute: typeof PlayerSongIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerSongIdRoute: PlayerSongIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/player/$song-id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/player/$song-id": {
      "filePath": "player/$song-id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
